version: '3.8'

services:
  netflix_backend_api:
    build: ./backend
    container_name: netflix_backend_api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=netflix_mysql_db
      - DB_USER=netflix_user
      - DB_PASSWORD=netflix_pass
      - DB_NAME=netflix_db
    depends_on:
      - netflix_mysql_db

  netflix_frontend_ui:
    build: ./frontend
    container_name: netflix_frontend_ui
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - netflix_backend_api

  # 👇 አዲሱ የ MySQL ዳታቤዝ አገልግሎት
  netflix_mysql_db:
    image: mysql:8.0
    container_name: netflix_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: netflix_db
      MYSQL_USER: netflix_user
      MYSQL_PASSWORD: netflix_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: