name: CI/CD Netflix Production Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: samicho23/netflix-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: samicho23/netflix-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push  
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 1. ሰርቨርህ ላይ ወዳለው የፕሮዳክሽን ፎልደር ግባ
            cd ~/netflix-production
            
            # 2. አዲሱን የዶከር ምስል ከ Docker Hub ሳብ
            docker compose pull
            
            # 3. አሮጌውን ኮንቴይነር አጥፍተህ በአዲሱ ምስል በሰከንድ ውስጥ አስነሳው
            docker compose up -d --remove-orphans
            
            # 4. በሰርቨሩ ላይ ያሉ አሮጌና ጥቅም የሌላቸውን ምስሎች በማጽዳት ቦታ አስለቅቅ
            docker system prune -f